services:
  - type: web
    name: smart-attendance-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
